### ISSUE TITLE
PCem doesn't detect ROMs files, even if files are in.

### ISSUE THREAD

**Issue by randomsomeone69** [sarah-walker-pcem/pcem#145]
**Describe the bug**
PCem doesn't detect ROMs files, even if files are in, and so it doesn't start except on a USB drive.

**To Reproduce**

1. Start program
2. See error

**Expected behavior**
Should boot on the PCem configuration menu.

**Host machine**

- OS: Windows 7 SP1
- Any version of PCem
- The CPU (Intel Core 2) doesn't support newer Intel virtualisation technologies.

**Additional context**
The problem also occurs on 86Box, derivate of PCem. I have filled a bug report, but the guys out there says that I have missplaced the roms files. I have a log file of the 86Box roms files, which is the same apart from some slight changes.
[roms output.log](https://github.com/sarah-walker-pcem/pcem/files/8670567/roms.output.log)

**Comment by leilei-** [comment]
Not a PCem bug.   PCem doesn't look for roms in categorized subfolders

**Comment by randomsomeone69** [comment]
oh.
but why it happen if i run only on my hard drive?

**Comment by ruben-balea** [comment]
It just occurred to me that it might be a configuration issue, there should be a file named pcem.txt in the same directory as pcem.exe
That file has a Paths section, to have the roms subfolder inside the same folder as pcem.exe the path should be blank, like:
[Paths]
roms_paths = 

Otherwise you can try to add the actual roms path like: roms_paths = D:\Documents\roms

The same applies to:
nvr_path = 
configs_path = 
logs_path = 
screenshots_path = 

Unless you want to have them in a specific location, for example to share them between several versions/copies of PCem it is better to leave them all blank.

If you don't have such a pcem.txt file download a copy of PCem of the same version you want to use and extract it from the zip file.

**Comment by Flo9696** [comment]
It should be the "pcem.cfg" file.

**Comment by ruben-balea** [comment]
> It should be the "pcem.cfg" file.

Whoops, I have Windows 10 set to open it with notepad and now the browser just calls it a text document and I didn't look at the actual file extension.

**Comment by TheoCGaming** [comment]
i'm trying to fix this issue under v17 and there's no pcem.cfg included in either version (linux *or* windows)
