### ISSUE TITLE
A portable version for PCEM V18 BETA?

### ISSUE THREAD

**Issue by ghost** [sarah-walker-pcem/pcem#182]
The latest version requires a configuration file in the user folder rather than the software folder, which means it will be lost when I simply copy the software folder to another computer, so I want this configuration file to be readable in the pcem folder so I can easily move this software.

**Comment by eddmanx** [comment]
Perhaps it could be implemented similar to some console emulators, by creating an empty `portable.txt` or `portable.ini` in the executable's folder.

**Comment by widardd** [comment]
I am surprised the config file even needs to have full paths rather than just something like ..\drives\.

**Comment by ruben-balea** [comment]
In v17 if you edit the config file you can use a path relative to the **PCem executable**, not to the config file.

For example if if your PCem executable is:
**c:\pcem\pcem.exe**
and your hard drive image for a Windows 95 machine is: **c:\pcem\drives\win95.img**
you can change it in the config file to:
**.\drives\win95.img**

Likewise if your PCem executable is:
**c:\pcem\pcem.exe**
but your hard drive image for a Windows 95 machine is:
**c:\pcem\my custom drives\another copy of win95.img**
with spaces in the path and/or file name you can change it in the config file to:
**.\my custom drives\another copy of win95.img** as is, **never put it in quotes**

I don't know if that still works like this in the latest version because I don't have it compiled right now, I deleted the folder by accident a few days ago and I would have to re-download and configure everything from scratch to test it but I can't do that right now.
But you can quickly check it yourself, change the path or name of a disk image file, edit the config file accordingly and see if it still works.

**Comment by widardd** [comment]
Awesome, that works. Why is this not the default behaviour? Odd.

**Comment by michael-manley** [comment]
This was fixed in commit 7a49e96

By default it puts the .pcem folder in the Windows home directory like Linux. But if you would like for it to be with the executable (ala Portable Mode) you just need to move your folders in .pcem
