### ISSUE TITLE
Upload Dev Builds to NasuTek CDN System

### ISSUE THREAD

**Issue by michael-manley** [sarah-walker-pcem/pcem#240]
Have completed builds get uploaded over to NasuTek CDN under https://cdn.ntgecdn.com/pcem-dev-builds for access to latest builds so they dont expire and be undownloadable.

**Comment by KoghaandSooga** [comment]
> Have completed builds get uploaded over to NasuTek CDN under https://cdn.ntgecdn.com/pcem-dev-builds for access to latest builds so they dont expire and be undownloadable.

How do you download the VNext whatever builds? All I get when clicking on that link is this message "This XML file does not appear to have any style information associated with it. The document tree is shown below." and a bunch of weird gobldygock that looks like this 
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>pcem-dev-builds</Name>
<Prefix/>
<Marker/>
<MaxKeys>1000</MaxKeys>
<IsTruncated>false</IsTruncated>
<Contents>
<Key>PCem-Debug-vNext-Ubuntu-46-33a4bc6c46fcf9eda4efcc915c7ae2ce50c51a36.tar.bz2</Key>
<LastModified>2023-11-02T20:28:31.289Z</LastModified>
<ETag>"4f3e1fc46f00379be962a481be2785eb-2"</ETag>
<Size>5548096</Size>
<Owner>

but nothing that looks like a download link. I KNOW there used to be download links before a year or two ago! What's going on here? Did it get pulled? 😕

**Comment by ruben-balea** [comment]
I don't know why the browser shows a XML file instead of a HTML file, possibly some misconfiguration on the server, but I have been using the file names included in that XML file, you can select and copy the file name for the build you want, like:
PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip

Then go to the address bar of your browser and type a slash after https://cdn.ntgecdn.com/pcem-dev-builds
and then paste the file name of the build you want after the slash, so it looks like:
https://cdn.ntgecdn.com/pcem-dev-builds/PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip

The press enter and the browser should start downloading that file.

**Comment by KoghaandSooga** [comment]
> I don't know why the browser shows a XML file instead of a HTML file, possibly some misconfiguration on the server, but I have been using the file names included in that XML file, you can select and copy the file name for the build you want, like: PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip
> 
> Then go to the address bar of your browser and type a slash after https://cdn.ntgecdn.com/pcem-dev-builds and then paste the file name of the build you want after the slash, so it looks like: https://cdn.ntgecdn.com/pcem-dev-builds/PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip
> 
> The press enter and the browser should start downloading that file.

Thanks! On a Celeron 300/366 I can actually get a fully working XP  on the stable one but on an older test one any emulated CPU lagged like hell.  I am evening playing Azada (a later XP era game) just fine on PCEM here's a screen to prove it that it's not just talk.
![Azada Menu](https://github.com/sarah-walker-pcem/pcem/assets/109556152/021bbd0a-1269-4353-a3ad-1ff2c3690834)
![Azada Chapter 1 scrolls found so far](https://github.com/sarah-walker-pcem/pcem/assets/109556152/ae56d46f-6014-4668-9c49-b481e0cfc10b)

The Voodoo 3 graphics are VERY beautiful in this setup! PC Games Wiki says the minimum specs is a Pentium 4 like what? https://www.pcgamingwiki.com/wiki/Azada No way it requires a P4 sorry but the wiki is lying thru it's teeth here!  Never mind it appears they changed the minimum requirements to a 600mhz but didn't specify the CPU. A lot of hidden object games on it are showing that now! Weird. I wonder what's going on.  Either way my Celeron 300/366 is still below even that requirement and other then the slow loading screen at startup the game plays beautiful. 

 I briefly raise the CPU to 500mhz which makes loading take only a little under a minute otherwise it takes about 3 minutes as the screen loads 5 boxes in and each box slowly shows up.  Why does 300mhz vs 500mhz make such a HUUUUUUUUUGGGGE difference in loading speed yet the rest of the game is just fine on either? 

There's also a sequel I never knew existed that I tested on PCEM and it works fine too which should be an even LATER XP game then this which was 2007 which I think was more into the Vista era or was it 7 by then? I think pretty much everyone skipped over Vista which is too bad it was such a broken OS as it's so beautiful. 

Okay I was wrong about which website. It's this website that claims it needs a minimum of Pentium 4 https://www.pcgamebenchmark.com/azada-system-requirements#:~:text=Azada%20system%20requirements%20state%20that,a%20minimum%20to%20run%20Azada.Azada minimum requirements
Memory: 128 MB
Graphics Card: ATI FireGL T2-128
CPU: Intel Pentium 4 2.00GHz
File Size: 65 MB
OS: Windows 2000/XP/Vista

PCEM doesn't have ANY of those except the XP part and 512MB of mem yet the game works and nothing weird happens except for how weird the puzzles are of course!

**Comment by KoghaandSooga** [comment]
> I don't know why the browser shows a XML file instead of a HTML file, possibly some misconfiguration on the server, but I have been using the file names included in that XML file, you can select and copy the file name for the build you want, like: PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip
> 
> Then go to the address bar of your browser and type a slash after https://cdn.ntgecdn.com/pcem-dev-builds and then paste the file name of the build you want after the slash, so it looks like: https://cdn.ntgecdn.com/pcem-dev-builds/PCem-vNext-Windows-MINGW64-49-c358285c8db2c147577b9fd8e6a0ed2eeecedd9c.zip
> 
> The press enter and the browser should start downloading that file.

PS. Why is there such a huge difference between the stable and experiment in speed on my XP setup? The same setup lags at 30 percent accuracy on the Next Build (even on Windows 98 it only improves to like 50 percent) while the stable one is 100 percent at Celeron 366 but starts to lag a bit at 400 on the same XP build? Remember this is the EXACT same hardware and hard disk and both PCEM versions have way different results.
