### ISSUE TITLE
Forum account creation disabled?

### ISSUE THREAD

**Issue by Randomno** [sarah-walker-pcem/pcem#259]
I'm not sure where else to ask this, but it seems like account creation on the forum is disabled. If so a note on the forum would be helpful. If not, could anyone help me find the button :)

**Comment by ruben-balea** [comment]
Yes, right now it seems to be disabled, maybe it was because some bots/scammers/spammers have registered recently...

But if you want to share or ask something related to the project you can do it right here, click on the "New issue" button and then on the link "[Open a blank issue.](https://github.com/sarah-walker-pcem/pcem/issues/new)" at the bottom. [Simply remember to follow the same rules as in the forum](https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665)

**Comment by KoghaandSooga** [comment]
It can't stare you in the face enough. It means quite literally PCEM is dead which is a shame.  It's one thing to be tired of working on a project but another to throw $@$# in people's faces who helped supporter her either directly or indirectly and make monkeys out of them because of a few rotten apples (Assuming the drama is true) which I don't even know what it is.

**Comment by KoghaandSooga** [comment]
We need a new PCEM of some sorts from the ground up with multi threading.

**Comment by KoghaandSooga** [comment]
> Yes, right now it seems to be disabled, maybe it was because some bots/scammers/spammers have registered recently...
> 
> But if you want to share or ask something related to the project you can do it right here, click on the "New issue" button and then on the link "[Open a blank issue.](https://github.com/sarah-walker-pcem/pcem/issues/new)" at the bottom. [Simply remember to follow the same rules as in the forum](https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665)

In other words taking the long route.

**Comment by KoghaandSooga** [comment]
> I'm not sure where else to ask this, but it seems like account creation on the forum is disabled. If so a note on the forum would be helpful. If not, could anyone help me find the button :)

Same but even if it wasn't disabled the forum was dead for years with only one or two topics per year.  I think it was a soft lie a new person took over just to get people to stop asking? I dunno. 🤷‍♂️ emu devs can get quite weird.
