### ISSUE TITLE
DST breaks differencing VHDs

### ISSUE THREAD

**Issue by leilei-** [sarah-walker-pcem/pcem#59]
**Describe the bug**
Differencing VHDs that try to load regress and invalidate their state whenever daylight savings time passes..

**To Reproduce**
1. Use PCem with differencing VHDs
2. Observe daylight savings time 
3. Attempt to use the same config after the hour was set back or forward

**Expected behavior**
The VHD working.

**Additional context**
Daylight savings time just kicked in and thus, this bug is now filed.  I suspected this on one post in the forum before.

**Comment by shermp** [comment]
Oof. This one's on me. (just noticed your post on VOGONS).

Can you please file an issue on [MiniVHD](https://github.com/shermp/MiniVHD)? It will affect more than just PCem.

**Comment by shermp** [comment]
Ok, looking back at the code (it's been a while), you should be able to "fix" this by deselecting and reselecting the VHD file in the config. It will ask if you want to readjust timestamps.

The other option is to delete the following from `hdd_file.c`:
```c
                                else if (err == MVHD_ERR_TIMESTAMP)
                                {
                                        pclog("VHD: Parent/child timestamp mismatch");
                                        mvhd_close(vhdm);
                                        hdd->f = NULL;
                                        return;
                                }
```
Basically, timestamp errors are not fatal, because it's fragile.
